### ISSUE TITLE
Strange Precedence

### ISSUE THREAD

**Issue by Sahasrara** [adzerk/zerkel#11]
This is the precedence specified in the grammar.  It seems like it's out of order.

> %left DOT
> %left '=' '<>' '=~' '!~'
> %left '<=' '>=' '<' '>'
> %left AND OR
> %left NOT
> %left CONTAINS LIKE

Six levels of precedence with DOT being the lowest precedence.  Is this on purpose?  Also NOT is left associative.  Is that correct too?

**Comment by Sahasrara** [comment]
C precedence for reference: https://en.cppreference.com/w/c/language/operator_precedence

**Comment by micha** [comment]
The `DOT` there is actually unused. But the rest is as intended.
